### ISSUE TITLE
flickering Track ID variable

### ISSUE THREAD

**Issue by philipphnz** [bitfocus/companion-module-tascamcd#8]
Hello, we connected a tascam ss-crd250n with companion (3.2.0) and want to display the current track-ID. When no media is loaded (no SD/USB/CD) there is a "0" as variable. When we put a USB Stick/SD/CD in the tascam, the number is flickering between a number (100/200/400) and very short time the track number. 
Here is a photo that shows the glitch as good as i could capture it:
![Foto 27 02 24, 15 03 17](https://github.com/bitfocus/companion-module-tascam-cd/assets/162289529/31bca0da-c4db-4988-bbcf-c587d210fdad)
Do you know that problem? Did we configered something wrong?

**Comment by phillipivan** [comment]
Hi @philipphnz can you please post an excerpt of the module logs with debug level turned on while this is occurring.

**Comment by philipphnz** [comment]
![IMG_2457](https://github.com/bitfocus/companion-module-tascam-cd/assets/162289529/c15e9d09-bc51-45d6-b768-d48bd97d60b8)
Thats the Log. Thanks for the fast response!

**Comment by phillipivan** [comment]
I can see the problem. Can you try the version in this fork and let me know how it goes (I dont have access to a unit):
https://github.com/phillipivan/companion-module-tascam-cd/tree/master

If you dont know how to build that let me know and I can email a build to you.

**Comment by philipphnz** [comment]
Thanks for the fast response! I would be very grateful if you could explain to me, how i build it!

**Comment by phillipivan** [comment]
There are instructions [here](https://github.com/bitfocus/companion-module-base/wiki) but it can take a while to get the environment setup and going the first time.
Happy to email a build to you if you message me your address.

**Comment by phillipivan** [comment]
[companion-module-tascam-cd.zip](https://github.com/bitfocus/companion-module-tascam-cd/files/14508961/companion-module-tascam-cd.zip)

Put this in a sub-folder inside a companion-modules-dev folder and point companion at it. 
If companion reports a version of 2.0.3 for the module then its running this version. Let me know how you go.

**Comment by philipphnz** [comment]
Thanks the module 2.0.3 is running, now i must go to the company where we installed the player and have to test it. I will keep contact to you if the bug is fixed!

**Comment by phillipivan** [comment]
When you test it can you please also check the Track Time variable, especially as you change modes with the Current Track Time Sense.

**Comment by phillipivan** [comment]
[companion-module-tascam-cd.zip](https://github.com/bitfocus/companion-module-tascam-cd/files/14533408/companion-module-tascam-cd.zip)
Actually try this. It *should* also do the follow:
End of Media feedback.
Timer mode (set with Current Track Time Sense) is saved in the device config, and the time polling should pick up this value.

**Comment by philipphnz** [comment]
Now I had the time to check the patch! It works great, thank you very much for your fast response and great work! The track id and the current timecode is working great. Do you need any evidence?

**Comment by phillipivan** [comment]
Nope. Thank you.

The updated module is in recent Betas, and will be in the next companion release.
